# Generated by Django 6.0.3 on 2026-04-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='customization_image',
            field=models.ImageField(blank=True, null=True, upload_to='customizations/'),
        ),
        migrations.AddField(
            model_name='order',
            name='gift_wrap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='customization_image',
            field=models.ImageField(blank=True, null=True, upload_to='order_customizations/'),
        ),
        migrations.AddField(
            model_name='product',
            name='enable_customization',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Set if there is a discount', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Current selling price', max_digits=10),
        ),
    ]
