# Generated by Django 6.0.3 on 2026-07-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cartitem_price_override_cartitem_product_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='custom_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='extra_letter_charges',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='letter_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='custom_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='extra_letter_charges',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='letter_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='enable_custom_message',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='enable_name_pricing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='enable_photo_upload',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='enable_size_selection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='extra_letter_price',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='product',
            name='included_letters',
            field=models.IntegerField(default=5),
        ),
    ]
