# Generated by Django 6.0.3 on 2026-07-22 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_cartitem_custom_name_cartitem_extra_letter_charges_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
