# Generated by Django 6.0.3 on 2026-07-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('shipping_charges', models.IntegerField(default=0)),
                ('production_time', models.CharField(default='3-7 Business Days', max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('gpay_upi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('phonepe_upi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('pinterest_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='cartitem',
            name='frame_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='led_option',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='thread_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='checklist_courier_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='checklist_customer_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='checklist_design_prepared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='checklist_images_downloaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='checklist_packed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='checklist_quality_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='checklist_string_art_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='checklist_tracking_added',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='courier_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='expected_delivery',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='frame_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='led_option',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='thread_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='enable_frame_color',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='enable_gift_option',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='enable_led_option',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='enable_thread_color',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_bestseller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new_arrival',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Ready to Make', 'Ready to Make'), ('Ready to Pack', 'Ready to Pack'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
