# Generated by Django 6.0.3 on 2026-07-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_businesssettings_cartitem_frame_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesssettings',
            options={'verbose_name_plural': 'Business Settings'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Ready to Make', 'Ready to Make'), ('Ready to Pack', 'Ready to Pack'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=30),
        ),
    ]
