# Generated by Django 6.0.3 on 2026-07-24 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_businesssettings_options_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='selected_addons',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='selected_clip_option',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='selected_photo_option',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customimage',
            name='order_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='selected_addons',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='selected_clip_option',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='selected_photo_option',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='enable_addon_option',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='enable_clip_option',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='enable_photo_option',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='enable_size_description',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='photo_option_default',
            field=models.CharField(default='with', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='photo_option_description_with',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='photo_option_description_without',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='photo_option_with_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='photo_option_without_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='photo_upload_allowed_formats',
            field=models.CharField(default='jpg,jpeg,png,webp', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='photo_upload_max',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='product',
            name='photo_upload_max_size',
            field=models.IntegerField(default=10, help_text='in MB'),
        ),
        migrations.AddField(
            model_name='product',
            name='photo_upload_min',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='photo_upload_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productsize',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProductAddonOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('additional_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('enabled', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addon_options', to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductClipOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('additional_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clip_options', to='shop.product')),
            ],
        ),
    ]
