# Generated by Django 6.0.3 on 2026-07-24 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_cartitem_selected_addons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customimage',
            name='original_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
