# Generated by Django 6.0.3 on 2026-04-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order_custom_text_customimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
