# Generated by Django 6.0.3 on 2026-04-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_cart_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='gift_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='is_gift',
            field=models.BooleanField(default=False),
        ),
    ]
